appName: springboot-demo
namespace: springboot-demo

git:
  appSrcRepository: https://github.com/thepierrre/demo-springboot-app

image:
  registry: default-route-openshift-image-registry.apps.ocp4.piotr-owczarc.com

host: apps.ocp4.piotr-owczarc.com
